############################################################
# Docker to try https://matomo.org
############################################################
FROM arm32v7/nginx
LABEL maintainer="Luong Bui"

RUN apt-get update && apt-get -y install vim nano zip

